:api_key: 50aa0ddaab2f67389573dd4a685dab99
:password: f6e1af5cc114e722fd05097386ea24b6
:theme_id: "13"
:preview_url: https://renatawistsemijoias.commercesuite.com.br/loja/loja.php?loja=1188544&opencode_theme=63e8f283853eb
:debug: true
